# Generated by Django 2.1.4 on 2019-08-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190805_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentpayable',
            name='date',
        ),
        migrations.AddField(
            model_name='chequepayable',
            name='date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
