# Generated by Django 2.1.4 on 2019-08-06 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_auto_20190806_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequepayable',
            name='approved_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
