# Generated by Django 2.1.4 on 2019-08-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_chequepayable_approved_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequepayable',
            name='cleared_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='chequepayable',
            name='signed_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
