# Generated by Django 2.1.4 on 2019-01-17 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactBuyer',
            fields=[
                ('contact_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Ac', 'active'), ('In', 'inactive')], default='In', max_length=2)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('payment_terms', models.CharField(max_length=50)),
                ('outstanding_receivable', models.FloatField()),
                ('outstanding_payable', models.FloatField()),
                ('place_of_contact', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=100)),
                ('relationship_manager', models.CharField(max_length=100)),
                ('gst_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContactVendor',
            fields=[
                ('contact_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contact_name', models.CharField(max_length=100)),
                ('website', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Ac', 'active'), ('In', 'inactive')], default='In', max_length=2)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('mobile', models.CharField(max_length=30)),
                ('payment_terms', models.CharField(max_length=50)),
                ('outstanding_receivable', models.FloatField()),
                ('outstanding_payable', models.FloatField()),
                ('place_of_contact', models.CharField(max_length=100)),
                ('currency_code', models.CharField(max_length=100)),
                ('relationship_manager', models.CharField(max_length=100)),
                ('gst_no', models.CharField(max_length=100)),
            ],
        ),
    ]
