# Generated by Django 2.1.4 on 2019-03-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactbuyer',
            name='place_of_contact',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contactvendor',
            name='place_of_contact',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
