# Generated by Django 2.1.4 on 2019-04-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20190326_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactvendor',
            name='freight_per_kg',
            field=models.FloatField(default=0.0),
        ),
    ]
