# Generated by Django 2.1.4 on 2019-05-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contactvendor_freight_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactbuyer',
            name='freight_per_kg',
            field=models.FloatField(default=0.0),
        ),
    ]
