# Generated by Django 2.1.4 on 2019-07-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contactbuyer_freight_per_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactbuyer',
            name='zoho_location',
            field=models.CharField(blank=True, default='okhla', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='contactvendor',
            name='zoho_location',
            field=models.CharField(blank=True, default='okhla', max_length=200, null=True),
        ),
    ]
