# Generated by Django 2.1.4 on 2019-06-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transporter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400, null=True)),
                ('address', models.CharField(blank=True, max_length=400, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=400, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=400, null=True)),
                ('website_url', models.CharField(blank=True, max_length=400, null=True)),
            ],
        ),
    ]
