# Generated by Django 2.1.4 on 2019-06-25 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_make'),
        ('deals', '0022_remove_salesorderproduct_quantity_dispatched'),
        ('servicedelivery', '0002_salesorderplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesOrderProductPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date_time', models.DateTimeField(blank=True, null=True)),
                ('shipped_date_time', models.DateTimeField(blank=True, null=True)),
                ('delivered_date_time', models.DateTimeField(blank=True, null=True)),
                ('planned_quantity', models.FloatField()),
                ('tracking_number', models.CharField(blank=True, max_length=300, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('freight', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reschedule_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('tracking_status', models.CharField(blank=True, max_length=300, null=True)),
                ('coafile', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.CoaFile')),
                ('salesorderproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.SalesOrderProduct')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicedelivery.Transporter')),
            ],
        ),
        migrations.RemoveField(
            model_name='salesorderplan',
            name='salesorderproduct',
        ),
        migrations.RemoveField(
            model_name='salesorderplan',
            name='transporter',
        ),
        migrations.DeleteModel(
            name='SalesOrderPlan',
        ),
    ]
