# Generated by Django 2.1.4 on 2019-06-26 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicedelivery', '0004_salesorderproductplan_lr_mailsent_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderproductplan',
            name='eta',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
