# Generated by Django 2.1.4 on 2019-07-19 09:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0027_auto_20190719_1449'),
        ('servicedelivery', '0005_salesorderproductplan_eta'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderProductPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_dispatch_date_time', models.DateTimeField(blank=True, null=True)),
                ('planned_receive_date_time', models.DateTimeField(blank=True, null=True)),
                ('dispatched_date_time', models.DateTimeField(blank=True, null=True)),
                ('received_date_time', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('planned_quantity', models.FloatField()),
                ('freight', models.FloatField()),
                ('dispatch_delay_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('receive_delay_reason', models.CharField(blank=True, max_length=500, null=True)),
                ('purchaseorderproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.PurchaseOrderProduct')),
                ('transporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicedelivery.Transporter')),
            ],
        ),
    ]
