# Generated by Django 2.1.4 on 2019-07-23 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicedelivery', '0006_purchaseorderproductplan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseorderproductplan',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
