# Generated by Django 2.1.4 on 2019-08-05 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_auto_20190805_1346'),
        ('servicedelivery', '0007_auto_20190723_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproductplan',
            name='paymentpayable',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.PaymentPayable'),
        ),
    ]
