# Generated by Django 2.1.4 on 2019-06-18 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_product_make'),
        ('contacts', '0004_contactbuyer_freight_per_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_selling_price', models.FloatField(blank=True, default=None, null=True)),
                ('average_selling_price', models.FloatField(blank=True, default=None, null=True)),
                ('frequency', models.FloatField(blank=True, default=None, null=True)),
                ('total_quantity', models.FloatField(blank=True, default=None, null=True)),
                ('total_so', models.FloatField(blank=True, default=None, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactBuyer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProductMonthSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('so_count', models.IntegerField()),
                ('total_quantity', models.FloatField()),
                ('total_sales', models.FloatField()),
                ('buyerproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.BuyerProduct')),
            ],
        ),
        migrations.CreateModel(
            name='BuyerProductMonthTarget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('targetprice', models.FloatField()),
                ('targetquantity', models.FloatField()),
                ('buyerproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.BuyerProduct')),
            ],
        ),
        migrations.CreateModel(
            name='DealVendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_terms', models.CharField(choices=[('Door Delivery', 'Door Delivery'), ('Ex-Godown', 'Ex-Godown'), ('FOR', 'FOR'), ('Local Transport', 'Local Transport')], default='', max_length=40)),
                ('payment_terms', models.CharField(blank=True, max_length=100)),
                ('time_created', models.DateTimeField(auto_now=True)),
                ('relationship_manager', models.CharField(blank=True, max_length=100)),
                ('date', models.DateField(null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactVendor', verbose_name='Vendor')),
            ],
        ),
        migrations.CreateModel(
            name='DealVendorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_name', models.CharField(blank=True, default='', max_length=300)),
                ('specs', models.CharField(blank=True, max_length=30)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('vendor_price', models.FloatField()),
                ('price_valid_till', models.DateField(blank=True, default=None, null=True)),
                ('lead_time', models.IntegerField(blank=True, null=True)),
                ('deal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.DealVendor')),
                ('make', models.ForeignKey(blank=True, default=None, max_length=50, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Make')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product')),
                ('unit', models.ForeignKey(blank=True, default=None, max_length=50, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='products.Unit')),
            ],
        ),
        migrations.CreateModel(
            name='EstimateProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='unselected', max_length=100)),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('pack_size', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=10)),
                ('pack_size', models.DecimalField(decimal_places=5, max_digits=10)),
                ('pickup_date', models.DateField(blank=True, default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='SalesOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(blank=True, null=True)),
                ('pack_size', models.IntegerField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactVendor')),
            ],
        ),
        migrations.CreateModel(
            name='VendorProductVariation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dealvendorproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.DealVendorProduct')),
                ('vendorproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.VendorProduct')),
            ],
        ),
        migrations.CreateModel(
            name='ZohoEstimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('estimate_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('estimate_url', models.CharField(max_length=300)),
                ('expiry_date', models.DateField()),
                ('delivery_terms', models.CharField(max_length=100)),
                ('total', models.FloatField()),
                ('tool_status', models.CharField(blank=True, default='', max_length=100)),
                ('salesperson', models.CharField(blank=True, default='', max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactBuyer')),
            ],
        ),
        migrations.CreateModel(
            name='ZohoPurchaseOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseorder_id', models.CharField(max_length=100)),
                ('purchaseorder_number', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('received_status', models.CharField(max_length=100)),
                ('billed_status', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('delivery_date', models.DateField()),
                ('total', models.FloatField()),
                ('purchaseorder_url', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ZohoSalesOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salesorder_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('salesorder_number', models.CharField(max_length=100)),
                ('reference_number', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('total', models.FloatField()),
                ('salesorder_url', models.CharField(blank=True, default='', max_length=300)),
                ('tool_status', models.CharField(blank=True, default='', max_length=100)),
                ('salesperson', models.CharField(blank=True, default='', max_length=100)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactBuyer')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='deals.ZohoEstimate')),
            ],
        ),
        migrations.AddField(
            model_name='zohopurchaseorder',
            name='salesorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.ZohoSalesOrder'),
        ),
        migrations.AddField(
            model_name='zohopurchaseorder',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.ContactVendor'),
        ),
        migrations.AddField(
            model_name='salesorderproduct',
            name='salesorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.ZohoSalesOrder'),
        ),
        migrations.AddField(
            model_name='salesorderproduct',
            name='vendorproductvariation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.VendorProductVariation'),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='purchaseorder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.ZohoPurchaseOrder'),
        ),
        migrations.AddField(
            model_name='estimateproduct',
            name='estimate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.ZohoEstimate'),
        ),
        migrations.AddField(
            model_name='estimateproduct',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='estimateproduct',
            name='vendorproductvariation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='deals.VendorProductVariation'),
        ),
    ]
