# Generated by Django 2.1.4 on 2019-06-18 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='purchaseorder',
        ),
        migrations.DeleteModel(
            name='PurchaseOrderProduct',
        ),
    ]
