# Generated by Django 2.1.4 on 2019-06-18 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_make'),
        ('deals', '0002_auto_20190619_0423'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_price', models.DecimalField(decimal_places=5, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=10)),
                ('pack_size', models.DecimalField(decimal_places=5, max_digits=10)),
                ('pickup_date', models.DateField(blank=True, default=None, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('purchaseorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.ZohoPurchaseOrder')),
            ],
        ),
    ]
