# Generated by Django 2.1.4 on 2019-06-19 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_make'),
        ('deals', '0003_purchaseorderproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='POProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
                ('purchaseorder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.ZohoPurchaseOrder')),
            ],
        ),
    ]
