# Generated by Django 2.1.4 on 2019-06-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_poproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poproduct',
            name='product',
        ),
    ]
