# Generated by Django 2.1.4 on 2019-06-19 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_make'),
        ('deals', '0005_remove_poproduct_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poproduct',
            name='purchaseorder',
        ),
        migrations.AddField(
            model_name='poproduct',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
