# Generated by Django 2.1.4 on 2019-06-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_auto_20190619_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poproduct',
            name='product',
        ),
        migrations.DeleteModel(
            name='POProduct',
        ),
    ]
