# Generated by Django 2.1.4 on 2019-06-19 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_auto_20190619_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderproduct',
            name='outward_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
