# Generated by Django 2.1.4 on 2019-06-19 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0008_salesorderproduct_outward_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderproduct',
            old_name='outward_datetime',
            new_name='outward_date_time',
        ),
    ]
