# Generated by Django 2.1.4 on 2019-06-19 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0009_auto_20190619_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderproduct',
            name='selling_pri',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
