# Generated by Django 2.1.4 on 2019-06-19 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0010_salesorderproduct_selling_pri'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salesorderproduct',
            old_name='selling_pri',
            new_name='so_selling_price',
        ),
    ]
