# Generated by Django 2.1.4 on 2019-06-20 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0011_auto_20190619_1713'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='pickup_date',
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='pickup_date_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='transporter_detail',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
