# Generated by Django 2.1.4 on 2019-06-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0012_auto_20190620_0840'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='freight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
