# Generated by Django 2.1.4 on 2019-06-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0013_purchaseorderproduct_freight'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderproduct',
            name='freight',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='salesorderproduct',
            name='transporter_detail',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
