# Generated by Django 2.1.4 on 2019-06-20 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0014_auto_20190620_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='received_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salesorderproduct',
            name='dispatched_status',
            field=models.BooleanField(default=False),
        ),
    ]
