# Generated by Django 2.1.4 on 2019-06-21 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0016_auto_20190621_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zohopurchaseorder',
            name='received_status',
        ),
    ]
