# Generated by Django 2.1.4 on 2019-06-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0017_remove_zohopurchaseorder_received_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesorderproduct',
            name='quantity_dispatched',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='salesorderproduct',
            name='quantity_to_dispatch',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
