# Generated by Django 2.1.4 on 2019-06-22 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0018_auto_20190621_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='received_status',
        ),
        migrations.RemoveField(
            model_name='salesorderproduct',
            name='dispatched_status',
        ),
    ]
