# Generated by Django 2.1.4 on 2019-06-24 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deals', '0019_auto_20190622_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerProductCoaFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='buyer/coa_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('buyerproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deals.BuyerProduct')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
