# Generated by Django 2.1.4 on 2019-06-24 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0020_buyerproductcoafile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderproduct',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='salesorderproduct',
            name='quantity_to_dispatch',
        ),
        migrations.RemoveField(
            model_name='salesorderproduct',
            name='transporter_detail',
        ),
    ]
