# Generated by Django 2.1.4 on 2019-06-25 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0021_auto_20190625_0131'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesorderproduct',
            name='quantity_dispatched',
        ),
    ]
