# Generated by Django 2.1.4 on 2019-06-28 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0023_remove_salesorderproduct_outward_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zohopurchaseorder',
            name='delivery_date',
        ),
    ]
