# Generated by Django 2.1.4 on 2019-07-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0024_remove_zohopurchaseorder_delivery_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohoestimate',
            name='zoho_location',
            field=models.CharField(blank=True, default='okhla', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='zohosalesorder',
            name='zoho_location',
            field=models.CharField(blank=True, default='okhla', max_length=100, null=True),
        ),
    ]
