# Generated by Django 2.1.4 on 2019-07-19 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0026_estimateproduct_estimate_selling_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='freight',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='pickup_date_time',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='quantity_received',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='quantity_to_receive',
        ),
        migrations.RemoveField(
            model_name='purchaseorderproduct',
            name='transporter_detail',
        ),
    ]
