# Generated by Django 2.1.4 on 2019-07-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0027_auto_20190719_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderproduct',
            name='tax_percentage',
            field=models.FloatField(default=0),
        ),
    ]
