# Generated by Django 2.1.4 on 2019-07-23 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0028_purchaseorderproduct_tax_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='pack_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='purchase_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='purchaseorderproduct',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
