# Generated by Django 2.1.4 on 2019-08-22 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0029_auto_20190723_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='zohosalesorder',
            name='open_status',
            field=models.BooleanField(default=False),
        ),
    ]
