# Generated by Django 2.1.4 on 2019-01-17 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('item_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('hsn_or_sac', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=2000)),
                ('unit', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Ac', 'active'), ('In', 'inactive')], default='In', max_length=2)),
                ('product_type', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=500)),
                ('stock_on_hand', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='group',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.ProductGroup'),
        ),
    ]
