# Generated by Django 2.1.4 on 2019-03-05 09:30

from django.db import migrations, models
import gdstorage.storage


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_coafile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coafile',
            name='file',
            field=models.FileField(storage=gdstorage.storage.GoogleDriveStorage(), upload_to='coa_files/'),
        ),
    ]
